input {
  file {
    path => "/var/lib/docker/containers/*/*.log"
    start_position => "beginning"
    sincedb_path   => "/usr/share/logstash/data/sincedb"
    codec => json
    exclude => ["/var/lib/docker/containers/*/*-json.log.*"]
    mode => "read"
    discover_interval => 10
    stat_interval => "5 second"
  }
}

filter {
  mutate { rename => { "log" => "message" } }

  grok {
    match => { "path" => "/var/lib/docker/containers/%{DATA:container_id}/%{DATA}-json.log" }
    tag_on_failure => []
  }

  mutate { gsub => ["message", "\r?\n$", ""] }
}

output {
  elasticsearch {
    hosts    => ["http://es01:9200"]
    user     => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index    => "docker-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
  stdout { codec => rubydebug }
}
